### ISSUE TITLE
vcap-services is now deprecated, but required in release-candidate branch

### ISSUE THREAD

**Issue by orsonkent** [cloudfoundry-community-attic/cf-services-release#16]
$ bundle exec cf bootstrap aws
.
.
.
Creating release cf-services-release
git clone -b release-candidate http://github.com/cloudfoundry/cf-services-release /tmp/cf-services-release
- git pull
  Already up-to-date.
- git submodule foreach --recursive git submodule sync
  Entering 'shared'
  Entering 'src/services'
  Synchronizing submodule url for 'govendor'
  Synchronizing submodule url for 'vendor/integration-test-support'
  Entering 'src/services/govendor'
  Entering 'src/services/vendor/integration-test-support'
  Entering 'src/services_warden'
  Entering 'src/tests'
  Synchronizing submodule url for 'assets'
  Entering 'src/tests/assets'
- git submodule update --init --recursive
  Submodule 'shared' () registered for path 'shared'
  Submodule 'src/services' () registered for path 'src/services'
  Submodule 'src/services_warden' () registered for path 'src/services_warden'
  Submodule 'src/tests' () registered for path 'src/tests'
  Submodule 'govendor' (https://github.com/cloudfoundry/vcap-services.git) registered for path 'govendor'
  Submodule 'vendor/integration-test-support' (https://github.com/cloudfoundry/vcap-services.git) registered for path 'vendor/integration-test-support'
  fatal: Needed a single revision
  Unable to find current revision in submodule path 'vendor/integration-test-support'
  Submodule 'assets' (https://github.com/cloudfoundry/vcap-yeti.git) registered for path 'assets'
  Failed to recurse into submodule path 'src/services'
  RuntimeError: Failed to run: cd /tmp/cf-services-release && ./update
  For more information, see ~/.cf/crash

**Comment by mycloudaccount** [comment]
I am also seeing this issue when running 

> bundle exec cf bootstrap aws
- git pull
  Already up-to-date.
- git submodule foreach --recursive git submodule sync
  Entering 'shared'
  Entering 'src/services'
  Synchronizing submodule url for 'govendor'
  Synchronizing submodule url for 'vendor/integration-test-support'
  Entering 'src/services/govendor'
  Entering 'src/services/vendor/integration-test-support'
  Entering 'src/services_warden'
  Entering 'src/tests'
  Synchronizing submodule url for 'assets'
  Entering 'src/tests/assets'
- git submodule update --init --recursive
  Submodule 'shared' () registered for path 'shared'
  Submodule 'src/services' () registered for path 'src/services'
  Submodule 'src/services_warden' () registered for path 'src/services_warden'
  Submodule 'src/tests' () registered for path 'src/tests'
  Submodule 'govendor' (https://github.com/cloudfoundry/vcap-services.git) registered for path 'govendor'
  Submodule 'vendor/integration-test-support' (https://github.com/cloudfoundry/vcap-services.git) registered for path 'vendor/integration-test-support'
  fatal: Needed a single revision
  Unable to find current revision in submodule path 'vendor/integration-test-support'
  Submodule 'assets' (https://github.com/cloudfoundry/vcap-yeti.git) registered for path 'assets'
  Failed to recurse into submodule path 'src/services'

**Comment by jfoley** [comment]
@orsonkent - it appears that only `vcap-services-base` is required by this release now. Closing this, if there is still an issue let us know.

@aramprice / @jfoley
