### ISSUE TITLE
generate_deployment_manifest does not generate usable manifest with AWS stub

### ISSUE THREAD

**Issue by pivotal-grapevine** [cloudfoundry-community-attic/cf-services-release#25]
We used the `generate_deployment_manifest` script to generate a services manifest for cf-services-release. After filling in some missing properties, we were able to get cf-services-release deployed. However, the release was unusable, as the mysql_gateway templates reference undefined nodes in the default AWS stub.

The undefined nodes were `properties.nats.address` and `properties.nats.port`. We were able to get these values from our cf deployment manifest and add them to our stub. However, the stub generated by `cf generate-stub aws` does not include these values, which makes sense since they're populated by the cf release.

**Comment by matt-royal** [comment]
The `cf generate-stub aws` command is not intended to be used with the newer `generate_deployment_manifest` scripts. For now, the only way to use `generate_deployment_manifest` is to create/fix a stub by hand, as you had to do. The product team is still considering how to address this situation.
