### ISSUE TITLE
Fix warden rootfs

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community-attic/cf-services-release#3]
I have not yet tested this release but saw the rootfs path does not references the rootfs package.

Related PR https://github.com/cloudfoundry/cf-release/pull/83

**Comment by drnic** [comment]
@rkoster I spent some time with Services team on Friday and they said that wardenized services wasn't being supported/implemented anymore (or at the moment).

**Comment by rkoster** [comment]
Okeay but there still is a [warden.yml](https://github.com/cloudfoundry/cf-services-release/blob/master/jobs/postgresql_node/templates/warden.yml) file in the postgress job. With a wrong [rootfs_path](https://github.com/cloudfoundry/cf-services-release/blob/master/jobs/postgresql_node/templates/warden.yml#L8).

**Comment by drnic** [comment]
AFAIK we still need warden for many services that don't have good colocated stories. @kushmerick also mentioned this
