### ISSUE TITLE
undefined method `acls'

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community-attic/cf-services-release#7]
i get the following error when using cf-service-release and following the readme.

```
Error 80006: Error filling in template `postgresql_gateway.yml.erb' for `services/0' (line 5: undefined method `acls' for nil:NilClass)
```

seems that this function is not defined
https://github.com/cloudfoundry/cf-services-release/blob/master/jobs/postgresql_gateway/templates/postgresql_gateway.yml.erb#L5

and i have no idea what acls should do

**Comment by drnic** [comment]
I believe the fix to this is in #5

**Comment by drnic** [comment]
I'm sorry I broke that :)

**Comment by ramonskie** [comment]
thanks will test it when your commit is merged
